name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NODE_ENV: production
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          NODE_ENV: production
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -i private_key $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /root/praktyki/Frontend
          pm2 delete "praktyki-frontend"
          pm2 start npm --name "praktyki-frontend" -- start
          pm2 save
          EOF
